baseurl = "http://douche.name"
languageCode = "en-us"
title = "Ruminations From a Tortured Mind"
canonifyurls = true

[params]
  author = "Sébastien Douche"
  copyright = "Copyleft (c) 20010 - 2014, Sébastien Douche. Licence CC-BY-NC-ND"
  gaCode = "UA-24575958-1"
